import { base } from "./constants";
import type { Bar } from "./types";

export const seedBars: Bar[] = [
  {
    id: "b1",
    name: "ShyShy",
    status: "visited",
    vibe: 8,
    value: 7,
    service: 9,
    food: 6,
    drinks: 7,
    bathroomBonus: 0,
    notes: "",
    ...base,
  },
  {
    id: "b2",
    name: "Jungle Bird",
    status: "visited",
    vibe: 6,
    value: 6,
    service: 7,
    food: 9,
    drinks: 7,
    bathroomBonus: 0,
    notes: "Spacious but really loud, nice food, options bad",
    ...base,
  },
  {
    id: "b3",
    name: "P.S. Kitchen",
    status: "visited",
    vibe: 4,
    value: 5,
    service: 5,
    food: 7,
    drinks: 7,
    bathroomBonus: 0,
    notes: "Vegan restaurant, decent food, decent drinks, super loud",
    ...base,
  },
  {
    id: "b4",
    name: "Rose Vale",
    status: "visited",
    vibe: 10,
    value: 7,
    service: 6,
    food: 6.5,
    drinks: 7,
    bathroomBonus: 0,
    notes: "",
    ...base,
  },
  {
    id: "b5",
    name: "Fig 19",
    status: "visited",
    vibe: 9,
    value: 7,
    service: 8,
    food: 3,
    drinks: 9,
    bathroomBonus: 0,
    notes: "",
    ...base,
  },
  {
    id: "b6",
    name: "Sir Henrys",
    status: "visited",
    vibe: 5.5,
    value: 7,
    service: 7,
    food: 7,
    drinks: 7,
    bathroomBonus: 2,
    notes: "",
    ...base,
  },
  {
    id: "b7",
    name: "The WooWoo",
    status: "visited",
    vibe: 9,
    value: 7.5,
    service: 6,
    food: 6,
    drinks: 6,
    bathroomBonus: 0,
    notes: "",
    ...base,
  },
  {
    id: "b8",
    name: "Malachy Back Room",
    status: "visited",
    vibe: 4,
    value: 10,
    service: 10,
    food: 4.5,
    drinks: 8,
    bathroomBonus: 0,
    notes: "",
    ...base,
  },
  {
    id: "b9",
    name: "Pineapple Club",
    status: "visited",
    vibe: 7,
    value: 8,
    service: 8,
    food: 5,
    drinks: 6,
    bathroomBonus: 0,
    notes: "",
    ...base,
  },
  {
    id: "b10",
    name: "Mr. Paradise",
    status: "visited",
    vibe: 6.5,
    value: 5,
    service: 6,
    food: 8,
    drinks: 6.5,
    bathroomBonus: 0,
    notes: "",
    ...base,
  },
  {
    id: "b11",
    name: "Banshee",
    status: "visited",
    vibe: 8.5,
    value: 8.5,
    service: 6,
    food: 3.5,
    drinks: 7,
    bathroomBonus: 0,
    notes: "really nice atmosphere but the food was very mid",
    ...base,
  },
  {
    id: "b12",
    name: "Old Town Bar",
    status: "visited",
    vibe: 6.5,
    value: 3.5,
    service: 6,
    food: 6.5,
    drinks: 7,
    bathroomBonus: 0,
    notes: "",
    ...base,
  },
  {
    id: "b13",
    name: "Lillie's Victorian Establishment",
    status: "visited",
    vibe: 9,
    value: 6,
    service: 9,
    food: 6.5,
    drinks: 6,
    bathroomBonus: 0,
    notes: "",
    ...base,
  },
  {
    id: "b14",
    name: "929",
    status: "visited",
    vibe: 9,
    value: 5.5,
    service: 8,
    food: 8.5,
    drinks: 8,
    bathroomBonus: 0,
    notes: "20/10, hot guy there",
    ...base,
  },
  {
    id: "b15",
    name: "Célon (Bryant Park Hotel Basement)",
    status: "visited",
    vibe: 9,
    value: 4,
    service: 9,
    food: 8,
    drinks: 8,
    bathroomBonus: 0,
    notes: "",
    ...base,
  },
  {
    id: "b16",
    name: "Sid Golds Request Room",
    status: "to-try",
    vibe: null,
    value: null,
    service: null,
    food: null,
    drinks: null,
    bathroomBonus: 0,
    notes: "",
    ...base,
    mapsLink: "https://maps.app.goo.gl/f6FM5FQSTSxA8L8F6",
  },
  {
    id: "b17",
    name: "Please Don't Tell (Hotdog Speakeasy)",
    status: "to-try",
    vibe: null,
    value: null,
    service: null,
    food: null,
    drinks: null,
    bathroomBonus: 0,
    notes: "",
    ...base,
    mapsLink: "https://maps.app.goo.gl/Y1ZcLk9hWY8mk5Vv9?g_st=ac",
  },
  {
    id: "b18",
    name: "A10 Kitchen",
    status: "to-try",
    vibe: null,
    value: null,
    service: null,
    food: null,
    drinks: null,
    bathroomBonus: 0,
    notes: "",
    ...base,
    mapsLink: "https://maps.app.goo.gl/L16byLwbc1kHYUYr5",
  },
  {
    id: "b19",
    name: "Ten Degrees",
    status: "to-try",
    vibe: null,
    value: null,
    service: null,
    food: null,
    drinks: null,
    bathroomBonus: 0,
    notes: "",
    ...base,
    mapsLink: "https://maps.app.goo.gl/mYhdYHCaMBDSKwm6A?g_st=ac",
  },
  {
    id: "b20",
    name: "Angels Share",
    status: "to-try",
    vibe: null,
    value: null,
    service: null,
    food: null,
    drinks: null,
    bathroomBonus: 0,
    notes: "",
    ...base,
    mapsLink: "https://maps.app.goo.gl/FPoVDSXT5j3a8qHw9?g_st=ac",
  },
  {
    id: "b21",
    name: "Katana Kitten",
    status: "to-try",
    vibe: null,
    value: null,
    service: null,
    food: null,
    drinks: null,
    bathroomBonus: 0,
    notes: "",
    ...base,
    mapsLink: "https://maps.app.goo.gl/8o7mvD7TGBkBHoHGA",
  },
  {
    id: "b22",
    name: "Izakaya MEW",
    status: "to-try",
    vibe: null,
    value: null,
    service: null,
    food: null,
    drinks: null,
    bathroomBonus: 0,
    notes: "",
    ...base,
    mapsLink: "https://maps.app.goo.gl/hc3V1X4nY4vrAoBz6?g_st=ac",
  },
  {
    id: "b23",
    name: "Lucky Cat",
    status: "to-try",
    vibe: null,
    value: null,
    service: null,
    food: null,
    drinks: null,
    bathroomBonus: 0,
    notes: "",
    ...base,
    mapsLink: "https://maps.app.goo.gl/dU2moYJoBgjvcQ966?g_st=ac",
  },
  {
    id: "b24",
    name: "Ippudo NY",
    status: "to-try",
    vibe: null,
    value: null,
    service: null,
    food: null,
    drinks: null,
    bathroomBonus: 0,
    notes: "",
    ...base,
    mapsLink: "https://maps.app.goo.gl/j1p1VbJUSEbTvKZW6?g_st=ac",
  },
];
